name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:  
  setup-build-publish:
    runs-on: ubuntu-latest

    steps:
    - 
      name: Login
      uses: docker/login-action@v3
      with:
        registry: sjc.vultrcr.com
        username: ${{ secrets.container_username }}
        password: ${{ secrets.container_key }}
    -
      name: Build and Publish
      run: docker build --file Dockerfile --tag realesrgan_server:$GITHUB_SHA
    -
      name: Publish
      run: docker push sjc.vultrcr.com/jetestcontainer/:realesrgan_server$GITHUB_SHA
