name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:  
  setup-build-publish:
    runs-on: ubuntu-latest

    steps:
    - 
      name: Login
      uses: docker/login-action@v3
      with:
        registry: sjc.vultrcr.com
        username: ${{ secrets.VULTR_USERNAME }}
        password: ${{ secrets.VULTR_KEY }}        
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ sjc.vultrcr.com }}/${{ github.repository }}/server:${{ github.sha }}
