name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:  
  build-and-push-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.vultr_url }}
          username: ${{secrets.vultr_username}}
          password: ${{secrets.vultr_key}}
      
      - name: Build Docker image
        run: docker build ${{env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          
      - name: Push Docker image
        run: docker push ${{env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
