name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:  
  build-and-push-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Build and push Docker image
        run: |
          docker login ${{ secrets.vultr_url }} -u ${{secrets.vultr_username}} -p ${{secrets.vultr_key}} 
          docker build ${{env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
