name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CONTAINER_USERNAME: ${{ secrets.container_username }}
  CONTAINER_KEY: ${{ secrets.container_key }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: docker login
      run: docker login "https://sjc.vultrcr.com/jetestcontainer -u $CONTAINER_USERNAME -p $CONTAINER_KEY"
    - name: Build the Docker image
      run: docker build --file Dockerfile --tag realesrgan_server:$GITHUB_SHA
    - name: Publish
      run: docker push "sjc.vultrcr.com/jetestcontainer/:realesrgan_server$GITHUB_SHA"
