on:
  push:
    branches: [ "main" ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Login
      run: |
        docker login https://sjc.vultrcr.com/testregistry1 -u ${{ secrets.REGISTRY_NEW_USERNAME }} -p ${{ secrets.REGISTRY_AUTH }}
