name: Build and Deploy
on:
  push:
    branches: [ "main" ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    
    steps:
      uses: docker/login-action@v3.0.0
      with:
        registry: $secrets.REGISTRY_URL
        username: $secrets.REGISTRY_USERNAME
        password: $secrets.REGISTRY_PASSWORD
    
