on:
  push:
    branches: [ "main" ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: docker login 
      run: docker push "https://sjc.vultrcr.com/jetestcontainer" -u $secrets.REGISTRY_USERNAME -p $secrets.REGISTRY_AUTH
